import {
    Truckload,
    ReeferTruckload,
    Flatbed,
    StepDeck,
    Specialized,
    Partial,
    ReeferPartial,
    LTL,
    ReeferLTL,
    Intermodal,
    Expedited,
    Drayage,
} from "./variables";
import {
    AB,
    BC,
    MB,
    NB,
    NL,
    NS,
    NT,
    NU,
    ON,
    PE,
    QC,
    SK,
    YT,
} from "./variables";
import {
    AL,
    AK,
    AZ,
    AR,
    CA,
    CO,
    CT,
    DC,
    DE,
    FL,
    GA,
    HI,
    ID,
    IL,
    IN,
    IA,
    KS,
    KY,
    LA,
    ME,
    MD,
    MA,
    MI,
    MN,
    MS,
    MO,
    MT,
    NE,
    NV,
    NH,
    NJ,
    NM,
    NY,
    NC,
    ND,
    OH,
    OK,
    OR,
    PA,
    RI,
    SC,
    SD,
    TN,
    TX,
    UT,
    VT,
    VA,
    WA,
    WV,
    WI,
    WY,
    PR,
} from "./variables";
import {
    AGS,
    BCN,
    BCS,
    CAM,
    CHP,
    CHH,
    CMX,
    COA,
    COL,
    DGO,
    GTO,
    GRO,
    HGO,
    JAL,
    EMX,
    MCH,
    MOR,
    NAY,
    NLE,
    OAX,
    PUE,
    QRO,
    ROO,
    SLP,
    SIN,
    SON,
    TAB,
    TAM,
    TLA,
    VER,
    YUC,
    ZAC,
} from "./variables";
import {
    notApplicable,
    Otay,
    Calexico,
    Nogales,
    ElPaso,
    Laredo,
    Hidalgo,
    Brownsville,
} from "./variables";

export const vendors = [
    {
        id: 1,
        company: "Totran Transportation",
        type: {
            asset_based: true,
            freight_broker: false,
        },
        contact: "Scott Pottie",
        email: "scottp@totran.ca",
        phone: "587-254-2390",
        domicile: {
            city: "Edmonton",
            state: AB,
            country: "Canada",
        },
        modes: [Flatbed, StepDeck, Specialized],
        hazmat: false,
        team_drivers: false,
        usa_bonded: false,
        can_bonded: false,
        coverage: {
            Canada: {
                country_code: "CAN",
                territory: [AB, BC, MB, NB, NL, NS, NT, NU, ON, PE, QC, SK, YT],
            },
            "United States": {
                country_code: "USA",
                territory: [WA, OR, CA, TX, OK],
            },
            Mexico: {
                country_code: "MEX",
                territory: [],
            },
        },
        borders: [notApplicable],
        core_lanes: ["AB:Anywhere", "BC:AB", "Edmonton, AB:Vancouver, BC"],
        banned_lanes: ["USA:USA", "BC:TX", "CAN:MEX"],
    },
    {
        id: 2,
        company: "Gigg Express",
        type: {
            asset_based: true,
            freight_broker: false,
        },
        contact: "Gurvinder Pritt",
        email: "gurv@giggexpress.ca",
        phone: "943-129-7834",
        domicile: {
            city: "Mississauga",
            state: ON,
            country: "Canada",
        },
        modes: [Truckload, LTL, Partial],
        hazmat: true,
        team_drivers: true,
        usa_bonded: true,
        can_bonded: true,
        coverage: {
            Canada: {
                country_code: "CAN",
                territory: [ON, QC],
            },
            "United States": {
                country_code: "USA",
                territory: [TX],
            },
            Mexico: {
                country_code: "MEX",
                territory: [EMX, CMX, JAL],
            },
        },
        borders: [notApplicable, Laredo],
        core_lanes: ["ON:Anywhere", "CAN:MEX"],
        banned_lanes: ["USA:USA", "MEX:MEX"],
    },
];
